import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navigations/Navbar";

import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-providers";

// uploadthing for not showing readiness of state
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";

// Toaster | Sonner
import Toaster from "@/components/ui/toaster";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${inter.className}, antialiased px-6 md:px-12 max-w-7xl mx-auto`
        )}
      >
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
