import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navigations/Navbar";

import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${inter.className}, antialiased px-6 md:px-12 max-w-7xl mx-auto`
        )}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
